import Head from 'next/head';

const AboutHead = () => (
  <Head>
    <title>About - Jupiter</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
);

export default function About() {
  return (
    <>
    <AboutHead/>
    <div className="p-5">
      <div className="mx-auto max-w-2xl">
        <h1 className="text-lg font-bold py-4">About Jupiter</h1>
        {[
          'Jupiter is a new tool that helps students make the most of what UTD has to offer. Students can interact with organizations on campus to discover how to best get involved.',
          'Jupiter provides a listing of campus organizations and ways to interact with them. This includes searching for organizations using key information, discovering events, and finding wayas to contact the org.',
        ].map((pText, i) => (
          <p key={i} className="mb-4">
            {pText}
          </p>
        ))}
      </div>
    </div>
    </>
  );
}
